name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_TOKEN: ${{ github.token }}
  CARGO_TERM_COLOR: always
permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: freebsd
            os: ubuntu-latest
            target: x86_64-unknown-freebsd
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build FreeBSD
        if: matrix.build == 'freebsd'
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: x86_64
          usesh: true
          mem: 8192
          sync: rsync
          prepare: |
            pkg install -y rust
          run: |
            cargo build --release --locked
            cp target/release/horse horse-freebsd
        
      - uses: moonrepo/setup-rust@v1
        if: matrix.build != 'freebsd'
        with:
          targets: ${{ matrix.target }}

      - name: Build
        if: matrix.build != 'freebsd'
        run: cargo build --release --locked

      - name: Build archive
        shell: bash
        run: |
          binary_name="horse"

          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.build }}" = "windows" ]; then
            mv "target/release/$binary_name.exe" "$dirname"
          elif [ "${{ matrix.build }}" = "freebsd" ]; then
            mv "horse-freebsd" "$dirname/$binary_name"
          else
            mv "target/release/$binary_name" "$dirname"
          fi

          if [ "${{ matrix.build }}" = "windows" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ASSET }}
